# Generated by Django 4.2.1 on 2023-05-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0003_headphone_phone_remove_notebook_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=10000)),
                ("image", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Headphone",
        ),
        migrations.DeleteModel(
            name="Notebook",
        ),
        migrations.DeleteModel(
            name="Phone",
        ),
        migrations.AddField(
            model_name="product",
            name="section_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="backend_api.productcategory",
            ),
        ),
    ]
