# Generated by Django 4.2.1 on 2023-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0004_product_productcategory_delete_headphone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="section_name_ru",
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
